import math
print("=" * 55)
print("POWER SYSTEM FAULT ANALYSIS")
print("Three-Phase Symmetrical Fault Analysis")
print("=" * 55)
S_base = float(input("100(MVA): "))
V_base = float(input("132(kV): "))
X_th = float(input("0.20(p.u.): "))
V_pre = float(input("0.1(p.u.): "))
I_base = (S_base * 1e6) / (math.sqrt(3) * V_base * 1e3)
I_fault_pu = V_pre / X_th
I_fault = I_fault_pu * I_base
fault_level = math.sqrt(3) * V_base * I_fault / 1000
fault_voltage = 0
print("\n" + "=" * 55)
print("FAULT ANALYSIS RESULTS")
print("=" * 55)
print(f"System Base Power: {S_base:.2f} MVA")
print(f"System Voltage: {V_base:.2f} kV")
print(f"Thevenin Reactance: {X_th:.3f} p.u.")
print(f"Pre-fault Voltage: {V_pre:.3f} p.u.")
print("-" * 55)
print(f"Base Current: {I_base:.2f} A")
print(f"Fault Current: {I_fault_pu:.2f} p.u.")
print(f"Actual Fault Current: {I_fault:.2f} A")
print(f": {I_fault / 1000:.3f} kA")
print(f"Short-Circuit Level: {fault_level:.2f} MVA")
print(f"Fault Voltage: {fault_voltage:.2f} p.u.")
print("-" * 55)
print("FAULT TYPE: Three-Phase Symmetrical (L-L-L) Fault")
print("FAULT CONDITION: Solid/Bolted Fault")
print("=" * 55)
print("\nIMPACT OF FAULT")
print("-" * 55)
print("1. Very high current flows through the faulted section.")
print("2. Voltage at the faulted bus falls almost to zero.")
print("3. Generators experience high electromagnetic stress.")
print("4. Transformers and busbars experience thermal and mechanical stress.")
print("5. Power transfer through the affected section is interrupted.")
print("6. Nearby loads may experience severe voltage dips.")
print("7. If not cleared quickly, system stability may be affected.")
print("\nPROTECTION METHODS")
print("-" * 55)
print("1. Busbar differential protection")
print("2. Overcurrent protection")
print("3. High-speed circuit breakers")
print("4. Current transformers")
print("5. Breaker-failure protection")
print("6. Backup protection")
print("\nFault analysis completed successfully.")